# common containers shared across all pega instances
# run $ docker-compose run pdm-install in order to install Pega Deployment Manager before everything else

version: '3.1'
services:

  pdm-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD
    networks:
      - pdm_net
    restart: unless-stopped

  pdm-install:
    image: ${PEGA_INSTALL_IMAGE}
    profiles:
      - install
    depends_on:
      - "pdm-db"
    environment:
      - ACTION=install
      - SYSTEM_NAME=pdm
      - PRODUCTION_LEVEL=2
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pdm-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pdm_net

  pdm:
    image: ${PEGA_RUN_IMAGE}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: pdm
    depends_on:
      - "pdm-db"
    environment:
      - NODE_TYPE=BackgroundProcessing,WebUser,Search
      - NODE_TIER=web
      - JDBC_URL=jdbc:postgresql://pdm-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pdm_net

networks:
  pdm_net:
    external:
      name: pega_common
