services:

  pega-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles:
      - web
    restart: unless-stopped

  cassandra:
    image: cassandra:3
    restart: unless-stopped

  pega:
    image: ${PEGA_RUN_IMAGE}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: ${CONTAINER_NAME}
    depends_on:
      - "pega-db"
    environment:
      - NODE_TYPE=BackgroundProcessing,WebUser,Search
      - NODE_TIER=${NODE_TIER}
      - JDBC_URL=jdbc:postgresql://pega-db:5432/postgres
      - CASSANDRA_CLUSTER=true
      - CASSANDRA_NODES=cassandra
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
      - EXTERNAL_STREAM
      - STREAM_BOOTSTRAP_SERVERS
      - STREAM_NAME_PATTERN
      - STREAM_SECURITY_PROTOCOL
      - STREAM_SASL_MECHANIS
    ports:
      - 8080:8080
    restart: unless-stopped

  pega-install:
    image: ${PEGA_INSTALL_IMAGE}
    depends_on:
      - "pega-db"
    environment:
      - ACTION=install
      - SYSTEM_NAME=pegaweb
      - PRODUCTION_LEVEL=2
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pega-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
      
  pega-upgrade:
    image: ${PEGA_UPGRADE_IMAGE}
    profiles:
      - upgrade
    depends_on:
      - "pega-db"
    environment:
      - ACTION=upgrade
      - UPGRADE_TYPE=in-place
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pega-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA

volumes:
  pgdata:
