# Use postgres/example user/password credentials
# sometimes need to call "truncate data.pr_data_stream_nodes;"
version: '3.1'
services:

  pega88-web-db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD
    networks:
      - pega88_net
    restart: unless-stopped

  pega88-cdh-db:
    image: postgres:13-alpine
    profiles:
      - cdh
    environment:
      - POSTGRES_PASSWORD
    networks:
      - pega88_net
    restart: unless-stopped

  cassandra88-cdh:
    image: cassandra:3
    profiles:
      - cdh
    networks:
      - pega88_net

  pega88-web:
    image: ${PEGA_RUN_IMAGE}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    container_name: pega88-web
    depends_on:
      - "pega88-web-db"
    environment:
      - NODE_TYPE=BackgroundProcessing,WebUser,Search
      - NODE_TIER=web
      - JDBC_URL=jdbc:postgresql://pega88-web-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pega88_net
    restart: unless-stopped

  pega88-cdh:
    image: ${PEGA_RUN_IMAGE}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    profiles:
      - cdh
    container_name: pega88-cdh
    depends_on:
      - "pega88-cdh-db"
    environment:
      - NODE_TYPE=ADM,Batch,RealTime,RTDG,Search,BackgroundProcessing
      - NODE_TIER=cdh
      - JDBC_URL=jdbc:postgresql://pega88-cdh-db:5432/postgres
      - CASSANDRA_CLUSTER=true
      - CASSANDRA_NODES=cassandra88-cdh
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pega88_net
    restart: unless-stopped

  pega88-web-install:
    image: ${PEGA_INSTALL_IMAGE}
    profiles:
      - install
    depends_on:
      - "pega88-web-db"
    environment:
      - ACTION=install
      - SYSTEM_NAME=pega88web
      - PRODUCTION_LEVEL=2
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pega88-web-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pega88_net

  pega88-cdh-install:
    image: ${PEGA_INSTALL_IMAGE}
    profiles:  
      - install
    depends_on:
      - "pega88-cdh-db"
    environment:
      - ACTION=install
      - SYSTEM_NAME=pega88cdh
      - PRODUCTION_LEVEL=2
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pega88-cdh-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
      - ADMIN_PASSWORD
    networks:
      - pega88_net
      
  pega-web-upgrade:
    image: ${PEGA_UPGRADE_IMAGE}
    profiles:
      - upgrade
    depends_on:
      - "pega88-web-db"
    environment:
      - ACTION=upgrade
      - UPGRADE_TYPE=in-place
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pega88-web-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
    networks:
      - pega88_net

  pega-cdh-upgrade:
    image: ${PEGA_UPGRADE_IMAGE}
    profiles:
      - upgrade
    depends_on:
      - "pega88-cdh-db"
    environment:
      - ACTION=upgrade
      - UPGRADE_TYPE=in-place
      - BYPASS_UDF_GENERATION=true
      - JDBC_URL=jdbc:postgresql://pega88-cdh-db:5432/postgres
      - JDBC_DRIVER_URI
      - DB_TYPE
      - JDBC_CLASS
      - DB_USERNAME
      - DB_PASSWORD
      - RULES_SCHEMA
      - DATA_SCHEMA
      - CUSTOMERDATA_SCHEMA
    networks:
      - pega88_net

networks:
  pega88_net:
    external:
      name: pega_common
